#!/bin/sh
FROM_ENCODING=utf-8
ISPELL_ENCODING=cp866
iconv -f $FROM_ENCODING -t $ISPELL_ENCODING <$1 >$1.$ISPELL_ENCODING
ispell $1.$ISPELL_ENCODING
iconv -f $ISPELL_ENCODING -t $FROM_ENCODING <$1.$ISPELL_ENCODING >$1
rm $1.$ISPELL_ENCODING
